// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Aponta a CLI do Prisma à base de produção sem passar a connection string
// pela linha de comandos. Mesmo interruptor dos scripts em scripts/:
//
//   PRISMA_TARGET=prod npx prisma migrate deploy        (bash)
//   $env:PRISMA_TARGET="prod"; npx prisma migrate deploy  (PowerShell)
//
// Sem a variável, a CLI continua a trabalhar sobre a base local do .env.
if (process.env.PRISMA_TARGET === "prod") {
  loadEnv({ path: ".env.production.local", override: true });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
